export class CustomSlide{
    noofslide:number;
    noofword:number;
    bullert:number;
    caudiance:number;
    fontfamily:string;
    position:string;
    header:string;
    headertext:string;
    footer:string;
    footertext:string;
    numbering:string;
    bcolorcheck:string;
    bcolor:string;
    fcolorcheck:string;
    fcolor:string;
    materialName:string;
    masterFirstName:string;
    masterSubName:string;
}